<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfhwoks\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfhwoks/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPfhwoks.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPfhwoks\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPfhwoks\appDevDebugProjectContainer([
    'container.build_hash' => 'Pfhwoks',
    'container.build_id' => 'b8cacf3d',
    'container.build_time' => 1562182481,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfhwoks');
